name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint and Test
        run: |
          pip install flake8
          flake8 . --max-line-length=120
      - name: Deploy to Streamlit Cloud
        run: echo "Deployed manually to Streamlit Cloud"  # Thay bằng script nếu có auto-deploy API